name: Generate Podcast Feed

on:
  push:
    branches:
      - main
    paths:
      - 'feed.yaml'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run Feed Generator
        uses: tu-usuario/podcast-generator@main
        with:
          email: '${{ github.actor }}@users.noreply.github.com'
          name: '${{ github.actor }}'
